/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Links = {
  _id: string;
  _type: "links";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  link?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type Socials = {
  _id: string;
  _type: "socials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  icon?: IconPicker;
  link?: string;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Slider = {
  _id: string;
  _type: "slider";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  author?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type PositionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "position";
};

export type Staff = {
  _id: string;
  _type: "staff";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  username?: Slug;
  role?: RoleReference;
  position?: PositionReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AnnouncementReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "announcement";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SliderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "slider";
};

export type SocialsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "socials";
};

export type LinksReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "links";
};

export type General = {
  _id: string;
  _type: "general";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  siteTitle?: string;
  announcement?: AnnouncementReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  sliders?: Array<
    {
      _key: string;
    } & SliderReference
  >;
  socials?: Array<
    {
      _key: string;
    } & SocialsReference
  >;
  links?: Array<
    {
      _key: string;
    } & LinksReference
  >;
  terms?: string;
  privacy?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  text?: string;
  socials?: Array<
    {
      _key: string;
    } & SocialsReference
  >;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
};

export type Credit = {
  _id: string;
  _type: "credit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  roll?: string;
  subtitle?: string;
  description?: string;
  display_picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Scholarship = {
  _id: string;
  _type: "scholarship";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Fundraiser = {
  _id: string;
  _type: "fundraiser";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  datetime?: string;
};

export type StudentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "student";
};

export type TeacherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teacher";
};

export type AlumniReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "alumni";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  one_liner?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featured_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author?: StudentReference | TeacherReference | AlumniReference;
  tags?: Array<string>;
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featured_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author?: StudentReference | TeacherReference | AlumniReference;
  tags?: Array<string>;
};

export type Alumni = {
  _id: string;
  _type: "alumni";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  roll_number?: string;
  username?: Slug;
  batch?: string;
  graduation_year?: number;
  role?: RoleReference;
  display_picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type DepartmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "department";
};

export type Teacher = {
  _id: string;
  _type: "teacher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  initials?: string;
  department?: DepartmentReference;
  username?: Slug;
  role?: RoleReference;
  position?: PositionReference;
  display_picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Department = {
  _id: string;
  _type: "department";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type HouseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "house";
};

export type Student = {
  _id: string;
  _type: "student";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  roll?: string;
  username?: Slug;
  batch?: string;
  house?: HouseReference;
  role?: RoleReference;
  position?: PositionReference;
  display_picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Position = {
  _id: string;
  _type: "position";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: RoleReference;
  color?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  color?: Color;
};

export type House = {
  _id: string;
  _type: "house";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  color?: Color;
  display_picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Links
  | Category
  | Socials
  | IconPicker
  | SanityImageAssetReference
  | Slider
  | SanityImageCrop
  | SanityImageHotspot
  | RoleReference
  | PositionReference
  | Staff
  | Slug
  | AnnouncementReference
  | CategoryReference
  | SliderReference
  | SocialsReference
  | LinksReference
  | General
  | Footer
  | Credit
  | Scholarship
  | Newsletter
  | Fundraiser
  | Event
  | StudentReference
  | TeacherReference
  | AlumniReference
  | Article
  | Announcement
  | Alumni
  | DepartmentReference
  | Teacher
  | Department
  | HouseReference
  | Student
  | Position
  | Color
  | Role
  | House
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/app/(app)/(root)/layout.tsx
// Variable: GENERAL_QUERY
// Query: *[_type == "general"][0]{  terms,  siteTitle,  categories[]->{    title  },  links[]->{    title,    link  }}
export type GENERAL_QUERY_RESULT = {
  terms: string | null;
  siteTitle: string | null;
  categories: Array<{
    title: string | null;
  }> | null;
  links: Array<{
    title: string | null;
    link: string | null;
  }> | null;
} | null;

// Source: ../web/src/app/(app)/(root)/page.tsx
// Variable: SLIDER_QUERY
// Query: *[_type == "general"][0]{  siteTitle,  sliders[]->{    title,    author,    image  },  categories[]->{    title  },  links[]->{    title,    link  }}
export type SLIDER_QUERY_RESULT = {
  siteTitle: string | null;
  sliders: Array<{
    title: string | null;
    author: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
  categories: Array<{
    title: string | null;
  }> | null;
  links: Array<{
    title: string | null;
    link: string | null;
  }> | null;
} | null;

// Source: ../web/src/app/(app)/(sub)/layout.tsx
// Variable: SUB_GENERAL_QUERY
// Query: *[_type == "general"][0]{  terms,  siteTitle,  categories[]->{    title  },  links[]->{    title,    link  }}
export type SUB_GENERAL_QUERY_RESULT = {
  terms: string | null;
  siteTitle: string | null;
  categories: Array<{
    title: string | null;
  }> | null;
  links: Array<{
    title: string | null;
    link: string | null;
  }> | null;
} | null;

// Source: ../web/src/components/home/cards/events.tsx
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] {  title,  datetime}
export type EVENTS_QUERY_RESULT = Array<{
  title: string | null;
  datetime: string | null;
}>;

// Source: ../web/src/components/home/main.tsx
// Variable: MAIN_ARTICLES_QUERY
// Query: *[_type == "article"] | order(_createdAt desc)[0...3]{  _id,  title,  one_liner,  featured_image,  "author": author->,  tags,  _createdAt}
export type MAIN_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  one_liner: string | null;
  featured_image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  author:
    | {
        _id: string;
        _type: "alumni";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        roll_number?: string;
        username?: Slug;
        batch?: string;
        graduation_year?: number;
        role?: RoleReference;
        display_picture?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: string;
        _type: "student";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        roll?: string;
        username?: Slug;
        batch?: string;
        house?: HouseReference;
        role?: RoleReference;
        position?: PositionReference;
        display_picture?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: string;
        _type: "teacher";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        initials?: string;
        department?: DepartmentReference;
        username?: Slug;
        role?: RoleReference;
        position?: PositionReference;
        display_picture?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | null;
  tags: Array<string> | null;
  _createdAt: string;
}>;

// Source: ../web/src/components/layout/footer.tsx
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{  text,  categories[]->{    title  },  socials[]->{    icon{      name,      provider    },    link,    title  }}
export type FOOTER_QUERY_RESULT = {
  text: string | null;
  categories: Array<{
    title: string | null;
  }> | null;
  socials: Array<{
    icon: {
      name: string | null;
      provider: string | null;
    } | null;
    link: string | null;
    title: string | null;
  }> | null;
} | null;

// Source: ../web/src/components/layout/footer.tsx
// Variable: PRIVACY_QUERY
// Query: *[_type == "general"][0]{  privacy}
export type PRIVACY_QUERY_RESULT = {
  privacy: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "general"][0]{\n  terms,\n  siteTitle,\n  categories[]->{\n    title\n  },\n  links[]->{\n    title,\n    link\n  }\n}':
      | GENERAL_QUERY_RESULT
      | SUB_GENERAL_QUERY_RESULT;
    '*[_type == "general"][0]{\n  siteTitle,\n  sliders[]->{\n    title,\n    author,\n    image\n  },\n  categories[]->{\n    title\n  },\n  links[]->{\n    title,\n    link\n  }\n}': SLIDER_QUERY_RESULT;
    '*[_type == "event"] {\n  title,\n  datetime\n}': EVENTS_QUERY_RESULT;
    '*[_type == "article"] | order(_createdAt desc)[0...3]{\n  _id,\n  title,\n  one_liner,\n  featured_image,\n  "author": author->,\n  tags,\n  _createdAt\n}': MAIN_ARTICLES_QUERY_RESULT;
    '*[_type == "footer"][0]{\n  text,\n  categories[]->{\n    title\n  },\n  socials[]->{\n    icon{\n      name,\n      provider\n    },\n    link,\n    title\n  }\n}': FOOTER_QUERY_RESULT;
    '*[_type == "general"][0]{\n  privacy\n}': PRIVACY_QUERY_RESULT;
  }
}
