/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AnnouncementReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "announcement";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SliderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "slider";
};

export type SocialsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "socials";
};

export type LinkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "link";
};

export type General = {
  _id: string;
  _type: "general";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  siteTitle?: string;
  siteDescription?: string;
  supportEmail?: string;
  logoText?: string;
  announcement?: AnnouncementReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  sliders?: Array<
    {
      _key: string;
    } & SliderReference
  >;
  socials?: Array<
    {
      _key: string;
    } & SocialsReference
  >;
  links?: Array<
    {
      _key: string;
    } & LinkReference
  >;
  terms?: string;
  privacy?: string;
  footerText?: string;
  footerSocials?: Array<
    {
      _key: string;
    } & SocialsReference
  >;
  footerCategories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Credit = {
  _id: string;
  _type: "credit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  roll?: string;
  subtitle?: string;
  description?: string;
  displayPicture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Socials = {
  _id: string;
  _type: "socials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform?: string;
  url?: string;
  label?: string;
  iconName?: string;
};

export type Slider = {
  _id: string;
  _type: "slider";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  author?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type NewsletterEmail = {
  _id: string;
  _type: "newsletterEmail";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  subscribed?: boolean;
};

export type Link = {
  _id: string;
  _type: "link";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  label?: string;
  openInNewTab?: boolean;
};

export type StudentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "student";
};

export type TeacherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teacher";
};

export type AlumniReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "alumni";
};

export type StaffReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "staff";
};

export type GuestReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "guest";
};

export type Scholarship = {
  _id: string;
  _type: "scholarship";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  raised?: number;
  amount?: number;
  deadline?: string;
  picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoLink?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  donors?: Array<{
    donor?:
      | StudentReference
      | TeacherReference
      | AlumniReference
      | StaffReference
      | GuestReference;
    amount?: number;
    currency?: "USD" | "EUR" | "GBP" | "INR" | "PKR" | "NPR";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subject?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishedAt?: string;
};

export type Fundraiser = {
  _id: string;
  _type: "fundraiser";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  goal?: number;
  raised?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  donors?: Array<{
    donor?:
      | StudentReference
      | TeacherReference
      | AlumniReference
      | StaffReference
      | GuestReference;
    amount?: number;
    currency?: "USD" | "EUR" | "GBP" | "INR" | "PKR" | "NPR";
    _key: string;
  }>;
  deadline?: string;
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type Guest = {
  _id: string;
  _type: "guest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  contactNumber?: string;
  organization?: string;
  notes?: string;
  role?: RoleReference;
};

export type PositionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "position";
};

export type Staff = {
  _id: string;
  _type: "staff";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  role?: RoleReference;
  position?: PositionReference;
  displayPicture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  location?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  oneLiner?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: CategoryReference;
  author?: StudentReference | TeacherReference | AlumniReference;
  tags?: Array<string>;
  publishedAt?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author?: StudentReference | TeacherReference | AlumniReference;
  tags?: Array<string>;
  publishedAt?: string;
};

export type Alumni = {
  _id: string;
  _type: "alumni";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  contactNumber?: string;
  batch?: string;
  graduatedYear?: number;
  roll?: string;
  role?: RoleReference;
  isActive?: boolean;
  displayPicture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type DepartmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "department";
};

export type Teacher = {
  _id: string;
  _type: "teacher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  initials?: string;
  email?: string;
  department?: DepartmentReference;
  role?: RoleReference;
  position?: PositionReference;
  displayPicture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Department = {
  _id: string;
  _type: "department";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type HouseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "house";
};

export type Student = {
  _id: string;
  _type: "student";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  roll?: string;
  batch?: string;
  house?: HouseReference;
  role?: RoleReference;
  email?: string;
  grade?: string;
  position?: PositionReference;
  displayPicture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Position = {
  _id: string;
  _type: "position";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  role?: RoleReference;
  description?: string;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type House = {
  _id: string;
  _type: "house";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Icon = {
  _type: "icon";
  name?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AnnouncementReference
  | CategoryReference
  | SliderReference
  | SocialsReference
  | LinkReference
  | General
  | SanityImageAssetReference
  | Credit
  | SanityImageCrop
  | SanityImageHotspot
  | Socials
  | Slider
  | NewsletterEmail
  | Link
  | StudentReference
  | TeacherReference
  | AlumniReference
  | StaffReference
  | GuestReference
  | Scholarship
  | Slug
  | Newsletter
  | Fundraiser
  | RoleReference
  | Guest
  | PositionReference
  | Staff
  | Event
  | Article
  | Category
  | Announcement
  | Alumni
  | DepartmentReference
  | Teacher
  | Department
  | HouseReference
  | Student
  | Position
  | Role
  | House
  | Icon
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/app/api/(frontend_queries)/get_articles/route.ts
// Variable: GET_ARTICLES_QUERY
// Query: *[  _type == "article" &&  publishedAt >= $startDate &&  publishedAt < $endDate &&  (    $search_string == "" ||    title match $searchPattern ||    oneLiner match $searchPattern ||    pt::text(content) match $searchPattern ||    category->title match $searchPattern ||    count(tags[@ match $searchPattern]) > 0  )]| order(publishedAt desc) {    _id,    title,    oneLiner,    "slug": slug.current,    publishedAt,    tags,    featuredImage,    "category": category->{      _id,      title,      "slug": slug.current    },    "author": author->{      _id,      _type,      "displayName": select(        _type == "student" => roll + " " + fullName,        _type == "teacher" => fullName,        _type == "alumnus" => fullName + " '" + batch,        fullName      ),    }  }
export type GET_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  oneLiner: string | null;
  slug: string | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  author:
    | {
        _id: string;
        _type: "alumni";
        displayName: string | null;
      }
    | {
        _id: string;
        _type: "student";
        displayName: string | null;
      }
    | {
        _id: string;
        _type: "teacher";
        displayName: string | null;
      }
    | null;
}>;

// Source: ../web/src/app/api/(frontend_queries)/get_events/route.ts
// Variable: GET_EVENTS_QUERY
// Query: *[_type == "event" && date >= "2026-07-13" && date < "2026-07-14"]{    date,    location,    "slug": slug.current,    title  }
export type GET_EVENTS_QUERY_RESULT = Array<{
  date: string | null;
  location: string | null;
  slug: string | null;
  title: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n  _type == "article" &&\n  publishedAt >= $startDate &&\n  publishedAt < $endDate &&\n  (\n    $search_string == "" ||\n    title match $searchPattern ||\n    oneLiner match $searchPattern ||\n    pt::text(content) match $searchPattern ||\n    category->title match $searchPattern ||\n    count(tags[@ match $searchPattern]) > 0\n  )\n]\n| order(publishedAt desc) {\n    _id,\n    title,\n    oneLiner,\n    "slug": slug.current,\n    publishedAt,\n    tags,\n    featuredImage,\n    "category": category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    "author": author->{\n      _id,\n      _type,\n      "displayName": select(\n        _type == "student" => roll + " " + fullName,\n        _type == "teacher" => fullName,\n        _type == "alumnus" => fullName + " \'" + batch,\n        fullName\n      ),\n    }\n  }\n': GET_ARTICLES_QUERY_RESULT;
    '\n  *[_type == "event" && date >= "2026-07-13" && date < "2026-07-14"]{\n    date,\n    location,\n    "slug": slug.current,\n    title\n  }\n': GET_EVENTS_QUERY_RESULT;
  }
}
